gtk3:
    extension: .scss
    output: colors
gtk4:
    extension: .scss
    output: colors
epiphany:
    extension: .scss
    output: user-stylesheet
tauon:
    extension: .ttheme
    output: base16
uosc:
    extension: .conf
    output: uosc
